//! Document retrieval endpoints (documents are generated by ApexEdge; POS prints locally).

use apex_edge_metrics::{
    DOCUMENT_OPERATIONS_TOTAL, DOCUMENT_OPERATION_DURATION_SECONDS, OP_GET_DOCUMENT,
    OP_LIST_ORDER_DOCUMENTS, OUTCOME_ERROR, OUTCOME_HIT, OUTCOME_NOT_FOUND,
};
use apex_edge_printing::generate_document;
use axum::{
    extract::{Path, State},
    Json,
};
use serde::Serialize;
use std::time::Instant;
use uuid::Uuid;

use crate::pos::AppState;

#[derive(Debug, Serialize)]
pub struct DocumentSummary {
    pub id: Uuid,
    #[serde(rename = "type")]
    pub type_: String,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub created_at: String,
    pub completed_at: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct DocumentResponse {
    pub id: Uuid,
    #[serde(rename = "type")]
    pub type_: String,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub content: Option<String>,
    pub error_message: Option<String>,
}

fn map_document_type_to_client_type(document_type: &str) -> String {
    match document_type {
        "customer_receipt" | "receipt" => "sales_receipt".to_string(),
        "gift_receipt" => "gift_receipt".to_string(),
        other => other.to_string(),
    }
}

pub async fn get_document(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Result<Json<DocumentResponse>, axum::http::StatusCode> {
    let start = Instant::now();
    let op = OP_GET_DOCUMENT;
    let result = apex_edge_storage::get_document(&state.pool, id).await;
    let (outcome, response) = match result {
        Ok(Some(doc)) => (
            OUTCOME_HIT,
            Ok(Json(DocumentResponse {
                id: doc.id,
                type_: map_document_type_to_client_type(&doc.document_type),
                document_type: map_document_type_to_client_type(&doc.document_type),
                status: doc.status,
                mime_type: doc.mime_type,
                content: doc.content,
                error_message: doc.error_message,
            })),
        ),
        Ok(None) => (OUTCOME_NOT_FOUND, Err(axum::http::StatusCode::NOT_FOUND)),
        Err(_) => (
            OUTCOME_ERROR,
            Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR),
        ),
    };
    metrics::counter!(DOCUMENT_OPERATIONS_TOTAL, 1u64, "operation" => op, "outcome" => outcome);
    metrics::histogram!(DOCUMENT_OPERATION_DURATION_SECONDS, start.elapsed().as_secs_f64(), "operation" => op);
    response
}

pub async fn list_order_documents(
    State(state): State<AppState>,
    Path(order_id): Path<Uuid>,
) -> Result<Json<Vec<DocumentSummary>>, axum::http::StatusCode> {
    let start = Instant::now();
    let op = OP_LIST_ORDER_DOCUMENTS;
    let result = apex_edge_storage::list_documents_for_order(&state.pool, order_id).await;
    let (outcome, response) = match result {
        Ok(docs) => (
            OUTCOME_HIT,
            Ok(Json(
                docs.into_iter()
                    .map(|d| DocumentSummary {
                        id: d.id,
                        type_: map_document_type_to_client_type(&d.document_type),
                        document_type: map_document_type_to_client_type(&d.document_type),
                        status: d.status,
                        mime_type: d.mime_type,
                        created_at: d.created_at,
                        completed_at: d.completed_at,
                    })
                    .collect(),
            )),
        ),
        Err(_) => (
            OUTCOME_ERROR,
            Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR),
        ),
    };
    metrics::counter!(DOCUMENT_OPERATIONS_TOTAL, 1u64, "operation" => op, "outcome" => outcome);
    metrics::histogram!(DOCUMENT_OPERATION_DURATION_SECONDS, start.elapsed().as_secs_f64(), "operation" => op);
    response
}

/// Synchronously generate a gift receipt for an existing order and return the new document summary.
pub async fn create_gift_receipt_document(
    State(state): State<AppState>,
    Path(order_id): Path<Uuid>,
) -> Result<Json<DocumentSummary>, axum::http::StatusCode> {
    let existing = apex_edge_storage::list_documents_for_order(&state.pool, order_id)
        .await
        .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
    let source = existing
        .iter()
        .find(|d| d.document_type == "customer_receipt" || d.document_type == "receipt")
        .or_else(|| existing.first())
        .ok_or(axum::http::StatusCode::NOT_FOUND)?;

    let payload: serde_json::Value = serde_json::from_str(&source.payload)
        .unwrap_or_else(|_| serde_json::json!({ "order_id": order_id.to_string() }));
    let payload_json = payload.to_string();

    let template =
        apex_edge_storage::get_print_template(&state.pool, state.store_id, "gift_receipt")
            .await
            .ok()
            .flatten();
    let (template_id, template_body, mime_type) = if let Some(ref t) = template {
        (t.template_id, t.template_body.as_str(), "application/pdf")
    } else {
        (
            Uuid::nil(),
            "Gift Receipt\nOrder: {{order_id}}\nTotal: {{total_cents}}",
            "text/plain",
        )
    };

    let doc_id = Uuid::new_v4();
    generate_document(
        &state.pool,
        doc_id,
        "gift_receipt",
        Some(order_id),
        source.cart_id,
        template_id,
        template_body,
        &payload_json,
        mime_type,
    )
    .await
    .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;

    let created = apex_edge_storage::get_document(&state.pool, doc_id)
        .await
        .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?
        .ok_or(axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(DocumentSummary {
        id: created.id,
        type_: map_document_type_to_client_type(&created.document_type),
        document_type: map_document_type_to_client_type(&created.document_type),
        status: created.status,
        mime_type: created.mime_type,
        created_at: created.created_at,
        completed_at: created.completed_at,
    }))
}
