//! Document retrieval endpoints (documents are generated by ApexEdge; POS prints locally).

use apex_edge_metrics::{
    DOCUMENT_OPERATIONS_TOTAL, DOCUMENT_OPERATION_DURATION_SECONDS, OP_GET_DOCUMENT,
    OP_LIST_ORDER_DOCUMENTS, OUTCOME_ERROR, OUTCOME_HIT, OUTCOME_NOT_FOUND,
};
use axum::{
    extract::{Path, State},
    Json,
};
use serde::Serialize;
use std::time::Instant;
use uuid::Uuid;

use crate::pos::AppState;

#[derive(Debug, Serialize)]
pub struct DocumentSummary {
    pub id: Uuid,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub created_at: String,
    pub completed_at: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct DocumentResponse {
    pub id: Uuid,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub content: Option<String>,
    pub error_message: Option<String>,
}

pub async fn get_document(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Result<Json<DocumentResponse>, axum::http::StatusCode> {
    let start = Instant::now();
    let op = OP_GET_DOCUMENT;
    let result = apex_edge_storage::get_document(&state.pool, id).await;
    let (outcome, response) = match result {
        Ok(Some(doc)) => (
            OUTCOME_HIT,
            Ok(Json(DocumentResponse {
                id: doc.id,
                document_type: doc.document_type,
                status: doc.status,
                mime_type: doc.mime_type,
                content: doc.content,
                error_message: doc.error_message,
            })),
        ),
        Ok(None) => (OUTCOME_NOT_FOUND, Err(axum::http::StatusCode::NOT_FOUND)),
        Err(_) => (
            OUTCOME_ERROR,
            Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR),
        ),
    };
    metrics::counter!(DOCUMENT_OPERATIONS_TOTAL, 1u64, "operation" => op, "outcome" => outcome);
    metrics::histogram!(DOCUMENT_OPERATION_DURATION_SECONDS, start.elapsed().as_secs_f64(), "operation" => op);
    response
}

pub async fn list_order_documents(
    State(state): State<AppState>,
    Path(order_id): Path<Uuid>,
) -> Result<Json<Vec<DocumentSummary>>, axum::http::StatusCode> {
    let start = Instant::now();
    let op = OP_LIST_ORDER_DOCUMENTS;
    let result = apex_edge_storage::list_documents_for_order(&state.pool, order_id).await;
    let (outcome, response) = match result {
        Ok(docs) => (
            OUTCOME_HIT,
            Ok(Json(
                docs.into_iter()
                    .map(|d| DocumentSummary {
                        id: d.id,
                        document_type: d.document_type,
                        status: d.status,
                        mime_type: d.mime_type,
                        created_at: d.created_at,
                        completed_at: d.completed_at,
                    })
                    .collect(),
            )),
        ),
        Err(_) => (
            OUTCOME_ERROR,
            Err(axum::http::StatusCode::INTERNAL_SERVER_ERROR),
        ),
    };
    metrics::counter!(DOCUMENT_OPERATIONS_TOTAL, 1u64, "operation" => op, "outcome" => outcome);
    metrics::histogram!(DOCUMENT_OPERATION_DURATION_SECONDS, start.elapsed().as_secs_f64(), "operation" => op);
    response
}
