//! Document retrieval endpoints (documents are generated by ApexEdge; POS prints locally).

use axum::{
    extract::{Path, State},
    Json,
};
use serde::Serialize;
use uuid::Uuid;

use crate::pos::AppState;

#[derive(Debug, Serialize)]
pub struct DocumentSummary {
    pub id: Uuid,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub created_at: String,
    pub completed_at: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct DocumentResponse {
    pub id: Uuid,
    pub document_type: String,
    pub status: String,
    pub mime_type: String,
    pub content: Option<String>,
    pub error_message: Option<String>,
}

pub async fn get_document(
    State(state): State<AppState>,
    Path(id): Path<Uuid>,
) -> Result<Json<DocumentResponse>, axum::http::StatusCode> {
    let doc = apex_edge_storage::get_document(&state.pool, id)
        .await
        .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
    let Some(doc) = doc else {
        return Err(axum::http::StatusCode::NOT_FOUND);
    };
    Ok(Json(DocumentResponse {
        id: doc.id,
        document_type: doc.document_type,
        status: doc.status,
        mime_type: doc.mime_type,
        content: doc.content,
        error_message: doc.error_message,
    }))
}

pub async fn list_order_documents(
    State(state): State<AppState>,
    Path(order_id): Path<Uuid>,
) -> Result<Json<Vec<DocumentSummary>>, axum::http::StatusCode> {
    let docs = apex_edge_storage::list_documents_for_order(&state.pool, order_id)
        .await
        .map_err(|_| axum::http::StatusCode::INTERNAL_SERVER_ERROR)?;
    Ok(Json(
        docs.into_iter()
            .map(|d| DocumentSummary {
                id: d.id,
                document_type: d.document_type,
                status: d.status,
                mime_type: d.mime_type,
                created_at: d.created_at,
                completed_at: d.completed_at,
            })
            .collect(),
    ))
}
