-- Carts
CREATE TABLE IF NOT EXISTS carts (
    id TEXT PRIMARY KEY NOT NULL,
    store_id TEXT NOT NULL,
    register_id TEXT NOT NULL,
    state TEXT NOT NULL,
    data TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Sync checkpoints (entity -> sequence)
CREATE TABLE IF NOT EXISTS sync_checkpoints (
    entity TEXT PRIMARY KEY NOT NULL,
    sequence INTEGER NOT NULL,
    updated_at TEXT NOT NULL
);

-- Outbox for order submission
CREATE TABLE IF NOT EXISTS outbox (
    id TEXT PRIMARY KEY NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL,
    next_retry_at TEXT,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT
);

-- Documents (generated by ApexEdge, fetched by POS for printing)
CREATE TABLE IF NOT EXISTS documents (
    id TEXT PRIMARY KEY NOT NULL,
    document_type TEXT NOT NULL,
    order_id TEXT,
    cart_id TEXT,
    status TEXT NOT NULL DEFAULT 'queued',
    template_id TEXT NOT NULL,
    payload TEXT NOT NULL,
    mime_type TEXT NOT NULL DEFAULT 'text/plain',
    content TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    error_message TEXT
);

-- Idempotency keys (POS commands)
CREATE TABLE IF NOT EXISTS idempotency (
    key TEXT PRIMARY KEY NOT NULL,
    response TEXT,
    created_at TEXT NOT NULL
);

-- Audit log (order finalization, submission, etc.)
CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_type TEXT NOT NULL,
    entity_id TEXT,
    payload TEXT,
    created_at TEXT NOT NULL
);
